// <auto-generated />
using System;
using KMSCalendar.MobileAppService.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KMSCalendar.MobileAppService.Migrations
{
    [DbContext(typeof(CalendarDbDataContext))]
    [Migration("20190530232101_AllModelsMigration")]
    partial class AllModelsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KMSCalendar.MobileAppService.Models.Entities.Assignment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClassId");

                    b.Property<string>("Description");

                    b.Property<DateTime>("DueDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("KMSCalendar.MobileAppService.Models.Entities.Class", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Period");

                    b.Property<string>("TeacherId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("KMSCalendar.MobileAppService.Models.Entities.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("KMSCalendar.MobileAppService.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KMSCalendar.MobileAppService.Models.Entities.Assignment", b =>
                {
                    b.HasOne("KMSCalendar.MobileAppService.Models.Entities.Class", "Class")
                        .WithMany("Assignments")
                        .HasForeignKey("ClassId");
                });

            modelBuilder.Entity("KMSCalendar.MobileAppService.Models.Entities.Class", b =>
                {
                    b.HasOne("KMSCalendar.MobileAppService.Models.Entities.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId");

                    b.HasOne("KMSCalendar.MobileAppService.Models.Entities.User")
                        .WithMany("EnrolledClasses")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
